[Icon Theme]
Name=Uniform+
Comment=Basis icon theme by 0rAX0. Actions, nimetypes from Flattr by Uri Herrera. Several icons from Emerald by vinceliuice, Super Flat Remix by daniruiz06. Mod. ZMA zma.05@mail.ru. 26.09.2015. CC Attribution-Noncommercial-Share Alike.
Version=2.0
Example=folder
Inherits=
Directories=apps/scalable

[apps/scalable]
Size=256
Context=Applications
Type=Scalable
MinSize=64
MaxSize=256
